name: Package Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Zip files
        run: |
          zip -r Client.zip Client
          zip -r MetroCUBEvania.apworld MetroCUBEvania

      - name: Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} Client.zip
          gh release upload ${{ github.event.release.tag_name }} MetroCUBEvania.apworld